#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://101.37.152.148:3306/cd_wms
  application:
    name: cd-ware
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.45.131:8848

mybatis-plus:
  #*mapper.xml文件的位置
  mapper-locations: classpath:/mapper/**/*.xml #classpath*:/mapper/**/*.xml表示所有微服务的classpath下的路径
  #配置主键自增
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000
