#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.45.131:3306/cd_ums
  application:
    name: cd-member
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.45.131:8848

mybatis-plus:
  #*mapper.xml文件的位置
  mapper-locations: classpath:/mapper/**/*.xml #classpath*:/mapper/**/*.xml表示所有微服务的classpath下的路径
  #配置主键自增
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000